# permissions for end users to edit memberclustermemberships.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memberclustermembership-editor-role
rules:
- apiGroups:
  - mng.io
  resources:
  - memberclustermemberships
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mng.io
  resources:
  - memberclustermemberships/status
  verbs:
  - get
