# permissions for end users to view memberclustermemberships.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memberclustermembership-viewer-role
rules:
- apiGroups:
  - mng.io
  resources:
  - memberclustermemberships
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mng.io
  resources:
  - memberclustermemberships/status
  verbs:
  - get
